### PR TITLE
adds geolocation methods

### PR DESCRIPTION
**Pull request by jlippold**
Hey Matt,

I don't know if you want these, because these are breaking changes. But throwing it out there anyway

### CODE REVIEW

**Comment by matt-kruse** [comment]
This is great, would love to merge it but don't want to break any apps using it. Could it also include a 'find' method so it's backwards-compatible?

**Comment by jlippold** [comment]
Ohh ok neat. Yea I can it backwards compatible, I didn't think you would accept the pull so I didn't bother initially. 

Also, I tied this into your alexa app server here: https://github.com/jlippold/alexa-app_find-my-phones

**Comment by matt-kruse** [comment]
These are things I originally wanted to put into the module but didn't have time, so I'm definitely interested! Your location/distance is great, and I wanted to go one step further - hook into a maps API to estimate driving time. So I could say "Alexa, how long til my wife gets home?" for example.

I officially submitted a "Find My Phone" skill to Amazon, but it was rejected because I had to store the icloud user/pass. If Apple ever supports OAuth for iCloud, then I think the app will be possible again.

**Comment by jlippold** [comment]
Yea travel time would be awesome. I wonder if openstreetmap can do travel time, since I think the google api requires a developers key. It also seems like find my friends uses a similar api to find my phone... maybe this module can hook into both. Give me a few days and I'll reopen this pull cleaner.

**Pull request closed without merging**
