### PR TITLE
Got alot of mail when i used your package so did this change

### PR DESCRIPTION
**Pull request by Mahlstrom**
Thanks for sharing this package, helped me alot.

The body from the validate post in checkSession was sent to onLogin as string and not an object.
Used JSON.parse to fix that.
Now the session are reused.

Best regards,
Magnus

### CODE REVIEW

**Comment by FlorianWendelborn** [comment]
I'll have to test this change later, this bug was the reason I stopped using this package. Thanks for sharing.

**Comment by fewstera** [comment]
@matt-kruse could you please merge this?

**Comment by matt-kruse** [comment]
done

**Comment by FlorianWendelborn** [comment]
@matt-kruse I'd assume @fewstera intended to request a `npm publish` too. 🙃

**Comment by matt-kruse** [comment]
Oops, got distracted and didn't do that part. Sorry. Just published 1.1.1 to npm.

**Pull request merged**
